### ISSUE TITLE
Add makepkg -g to update checksum

### ISSUE THREAD

**Issue by pheiduck** [edlanglois/pkgbuild-action#4]
would be nice if it has the ability to update the checksum of the pkg with command `makepkg -g >> PKGBUILD`

**Comment by edlanglois** [comment]
At the moment I'm avoiding anything that changes files into the repository. If `.SRCINFO` is wrong it just errors out rather than fix it, for example. I think it would be adding too much complexity for this action to automatically create new commits. A "pkgbuild fixer/updater" seems reasonable but would be better as a separate action.

So I'm going to close this because I don't plan on implementing it, but feel free to fork the repo and try it out! If it's possible to implement in a way that isn't too complex or surprising, and is opt-in with an option then I'd consider it but really I think best as a standalone action.

As an aside, I'm not sure it's a great idea to automatically update checksums without any user interaction. The point of the checksum is to ensure the downloaded files are what they should be so the pkgbuild author should ideally verify those checksums in some way. I generally try to use checksums listed on the upstream website. Otherwise you could end up with an attacker messing with the file that GitHub downloads, and then bad checksums will be inserted directly into the pkgbuild. If you're using https then that's unlikely but then what's the point of having a checksum? I'm not 100% opposed to having a potential footgun like that as an optional feature but it's not something I really endorse either.
